name: React Frontend Deployment to S3

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    #Required in order to retrieve keys stored on Github
    permissions:
      id-token: write
      contents: write

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build --if-present
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #Needs to be the same as the S3 region location
          aws-region: us-east-1
      - run: aws s3 sync ./build s3://reactjsauthenticator
